USE [weppo]
GO

/****** Object:  Table [dbo].[FAVOURITE]    Script Date: 06.02.2022 17:51:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FAVOURITE](
	[user_id] [int] NULL,
	[product_id] [int] NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FAVOURITE]  WITH CHECK ADD  CONSTRAINT [FK_FAVOURITE_PRODUCT] FOREIGN KEY([product_id])
REFERENCES [dbo].[PRODUCT] ([id])
GO

ALTER TABLE [dbo].[FAVOURITE] CHECK CONSTRAINT [FK_FAVOURITE_PRODUCT]
GO

ALTER TABLE [dbo].[FAVOURITE]  WITH CHECK ADD  CONSTRAINT [FK_FAVOURITE_USER] FOREIGN KEY([user_id])
REFERENCES [dbo].[USER] ([id])
GO

ALTER TABLE [dbo].[FAVOURITE] CHECK CONSTRAINT [FK_FAVOURITE_USER]
GO

